add barcode custom field
new-black/eva-defaults pull request #66
Opened 2024-02-13 09:49 UTC by popadavid1

https://n6k.atlassian.net/browse/OPTR-28901

2024-02-23 17:49 UTC, omeaart requested changes
Converted: true

Should be added

2024-03-14 15:12 UTC, omeaart commented
@popadavid1 Will this be fixed? Or can this be closed?

2024-03-20 08:41 UTC, suciuradu00 approved these changes

2024-03-20 08:45 UTC, omeaart approved these changes

2024-03-20 08:45 UTC, merged