feat(OPTR-27999): Partial Payment setting
new-black/eva-defaults pull request #67
Opened 2024-02-20 10:38 UTC by suciuradu00

https://n6k.atlassian.net/browse/OPTR-27999

2024-02-23 17:50 UTC, omeaart requested changes
Converted: true

Needs to be added

2024-03-14 15:12 UTC, omeaart commented
@suciuradu00 Will this be fixed? Or can this be closed?

2024-03-19 11:51 UTC, suciuradu00 commented
@omeaart done

2024-03-20 08:45 UTC, omeaart approved these changes

2024-03-20 08:46 UTC, merged