fix(): added app setting to show/hide debug panel in app suite
new-black/eva-defaults pull request #68
Opened 2024-02-26 15:10 UTC by janvandenberg

2024-03-14 10:38 UTC, omeaart requested changes
Converted: true is missing

2024-03-19 11:58 UTC, janvandenberg commented
@omeaart default is false, not true

2024-03-19 11:59 UTC, omeaart commented
> @omeaart default is false, not true

I don't care about the default. I care about the property converted. It is required for new added settings. And it should be true

2024-03-20 08:46 UTC, omeaart approved these changes

2024-03-20 08:46 UTC, merged